name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: gcc -o configure configure.c ./JSON_hashing/site_hash.c ./JSON_hashing/id_hash.c
    - name: configure
      run: ./configure
